apiVersion: v1
kind: Service
metadata:
  name: dremio-service
  namespace: dremio
spec:
  selector:
    app: dremio
  ports:
  - name: ui
    port: 9047
    targetPort: 9047
    nodePort: 30947
  - name: client
    port: 31010
    targetPort: 31010
    nodePort: 31010
  - name: server
    port: 32010
    targetPort: 32010
    nodePort: 32010
  - name: flight
    port: 45678
    targetPort: 45678
    nodePort: 32678
  type: NodePort
