apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: active-flow
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306       # Port sur le service
      targetPort: 3306 # Port sur le pod
      nodePort: 30306  # Port sur le noeud (optionnel, sinon Kubernetes en choisit un automatiquement)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: active-flow
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      containers:
      - image: mysql:9
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
