apiVersion: v1
kind: Service
metadata:
  name: minio-amoaman-nodeport
  namespace: minio-tenant
  labels:
    app: minio
    v1.min.io/tenant: minio-amoaman
spec:
  type: NodePort
  selector:
    v1.min.io/tenant: minio-amoaman
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 30900  # Choisis un port libre entre 30000–32767
