# Trino Deployment & Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalogs
  namespace: trino
data:
  iceberg.properties: |
    connector.name=iceberg
    iceberg.catalog.type=nessie
    iceberg.nessie-catalog.uri=http://195.35.1.215:19120/api/v2
    iceberg.nessie-catalog.ref=main
    iceberg.nessie-catalog.default-warehouse-dir=s3a://warehouse/
    fs.native-s3.enabled=true
    s3.endpoint=http://195.35.1.215:30900
    s3.region=us-east-1
    s3.path-style-access=true
    s3.aws-access-key=lakehouse
    s3.aws-secret-key=lakehouse-secret-key