---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: trino
spec:
  type: NodePort
  ports:
    - name: trino-http
      port: 8080
      targetPort: 8080
      nodePort: 30808
  selector:
    app: trino