apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metabase
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        env:
        - name: MB_DB_TYPE
          value: "postgres"
        - name: MB_DB_DBNAME
          value: "metabaseappdb"
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_USER
          value: "metabase"
        - name: MB_DB_PASS
          value: "mysecretpassword"
        - name: MB_DB_HOST
          value: "postgres"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: random-device
          mountPath: /dev/random
          readOnly: true
        - name: metabase-storage
          mountPath: /metabase-data
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: random-device
        hostPath:
          path: /dev/urandom
      - name: metabase-storage
        persistentVolumeClaim:
          claimName: metabase-pvc
