apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
      - name: nessie
        image: projectnessie/nessie:latest
        ports:
        - containerPort: 19120
        env:
        - name: QUARKUS_PROFILE
          value: "prod"
        - name: QUARKUS_HTTP_PORT
          value: "19120"
        - name: QUARKUS_LOG_CONSOLE_FORMAT
          value: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n"
        - name: QUARKUS_LOG_LEVEL
          value: "INFO"
        - name: QUARKUS_DATASOURCE_DB_KIND
          value: "rocksdb"
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: "jdbc:rocksdb:file:///nessie/data"
        - name: QUARKUS_DATASOURCE_USERNAME
          value: "nessie"
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: "nessie"
        volumeMounts:
        - name: nessie-storage
          mountPath: /nessie/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: nessie-storage
        persistentVolumeClaim:
          claimName: nessie-pvc