apiVersion: v1
kind: PersistentVolume
metadata:
  name: nessie-pv
  namespace: nessie
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  hostPath:
    path: /data/nessie-data