apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessie-pvc
  namespace: nessie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn