# Nessie Service
apiVersion: v1
kind: Service
metadata:
  name: nessie-service
  namespace: nessie
spec:
  selector:
    app: nessie
  ports:
  - port: 19120
    targetPort: 19120
    nodePort: 30120
  type: NodePort