---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: glpi-pvc
 namespace: helpdesk
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-pvc
 namespace: helpdesk
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
