

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
          ports:
            - containerPort: 8123  # HTTP interface
            - containerPort: 9000  # Native TCP interface
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: clickhouse-pvc

      # Add resource limits and requests
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "16Gi"
          cpu: "4"


