
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce  # Longhorn ne supporte pas ReadWriteMany nativement (voir ci-dessous)
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---