
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe-worker-long
  namespace: erp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe-worker-long
  template:
    metadata:
      labels:
        app: frappe-worker-long
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: init
        image: frappe/erpnext:v15.59.0
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        command: ["bench", "worker", "--queue", "long"]
        env:
        - name: DB_HOST
          value: "mariadb.erp-dev.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "_decae369018f2248" # Verify after frappe-init runs
        - name: DB_USER
          value: "_decae369018f2248" # Verify after frappe-init runs
        - name: DB_PASSWORD
          value: "Od6irMm3jW4rlMB1" # Verify after frappe-init runs
        - name: REDIS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: frappe-config
              key: redis_queue_url
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
        - name: logs
          mountPath: /home/frappe/frappe-bench/logs
        - name: frappe-apps
          mountPath: /home/frappe/frappe-bench/apps
        - name: frappe-config-vol
          mountPath: /home/frappe/frappe-bench/sites/common_site_config.json
          subPath: common_site_config.json

      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: frappe-sites
      - name: logs
        persistentVolumeClaim:
          claimName: frappe-logs
      - name: frappe-apps
        persistentVolumeClaim:
          claimName: frappe-apps
      - name: frappe-config-vol
        configMap:
          name: frappe-config
          items:
            - key: common_site_config.json
              path: common_site_config.json

---
